### ISSUE TITLE
Vulcan config proposal

### ISSUE THREAD

**Issue by amadeovezz** [mountetna/monoetna#1311]
## Purpose

To get consensus on what the Vulcan config should look like. 

Context:

Typically a snakemake pipeline is just a Snakefile, a config and some scripts. A vulcan pipeline is a snakemake pipeline, with a `vulcan_config.yaml`.  The UI does not care and should not care about the details of a snakemake pipeline. The config is meant to act as a medium that:

- Informs the UI what jobs and parameters the snakemake pipelines needs to run.
- Informs the UI how to render components for job parameterization.
- Informs the UI when javascript jobs need to run.

### Example

We will use the single cell viz workflow as an example. Note this is border line pseudo code and many of the real parameters have been omitted. 

#### Snakefile

```
get_record:
  input:
    record_name=config["get_record"]["record_name"]
  output:
    single_cell_object="output/single_cell_output.json"
  script:
    "scripts/magma_puller.rb"

rule get_dataset_and_summarize:
  input:
    single_cell_object="output/single_cell_object.json"
  output:
    plotting_options="output/plotting_options.json",
    discrete_metadata_summary="output/discrete_metadata_summary.json",
    all_opts="output/all_opts.json",
    scdata="output/scdata.Rds",
  params:
    dataset_name=config["get_dataset_and_summarize"]["dataset_name"]
  script:
    "scripts/get_dataset_and_summarize.R -name params["dataset_name"]

rule make_plot:
  input:
    plot_setup="output/plot_setup.json",
    scdata="output/scdata.Rds",
  output:
    plot_out="output/plot.out",
    legend_png="output/legend.png",
    plot_png="output/plot.png",
    plot_Rds="output/plot.Rds"
  script:
    "scripts/make_dittoSeq_plot.R"
```

#### `vulcan_config`

```yaml

get_single_cell_record:
  display: "object selection"
  doc: "fetches a single cell object from magma"
  params:
    record_name:
      display: "name of record to target"
      ui_component: "text"


get_dataset_and_summarize:
  job_type: "snake"
  doc: "performs some computation on the single cell record"
  params:
    dataset_name:
      ui_component: "text"

make_plot:
  doc: "create plot in dittoseq"
  display: "Set plot options"
  params:
      set_plot_options:
        display: "Set plot options"
        ui_component: "ui-queries/any-dittoseq.tsx"
        input:
          data_frame="output/discrete_metadata_summary.json",
          all_opts="output/all_opts.json"
        output:
          plot_setup="output/plot_setup.json"

download_plot:
  run:
    script: "ui-queries/download_plot.tsx"
    input:
      plot_out="output/plot.out",
      legend_png="output/legend.png",
      plot_png="output/plot.png"


```

### `vulcan_config.yaml` rules and yaml keys explained

1. All jobs must be listed in order in the yaml (top level keys). This tells the UI the order and dependency between jobs. The name if the job must also match the name of the snakemake job. For jobs that do not require parameterization, you must still list the job, ex: `get_dataset_and_summarize`. 

2. Parameters can be static or dynamic. Static parameters are components that can be pre-rendered without any input. An example of this is the "text" ui_component. Dynamic parameters require some input before rendering. There are two types of dynamic parameters:
 i. Ones must fetch inputs from a workspace, an example of this is `set_plot_option` parameter. 
 ii. Ones that make an API call to our services (ie: grab some data from magma to populate a dropdown)

3. To run javascript code you must use the `run` keyword, and list your `script`, and `input`  and `output` if exists. See the `download_plot` top level key.

4. Both dynamic parameters and javascript scripts must write their output and input back to the `output` directory in the snakemake workspace. This is the single source of truth for all inputs and outputs.

#### Open questions:

- Do we like the nesting of dynamic parameters?

**Comment by amadeovezz** [comment]
Adding some notes here post team discussion.

### Vulcan's philosophy

Originally we wanted it such that any pipeline author (aware of the DL services or not) could write a snakemake pipeline, and then drop in a `vulcan_config.yaml` that would make the pipeline "just work" on Vulcan. Unfortunately, this is really tricky to do, so as an alternative, we have established:

- It is okay to make changes to the snakefile and the pipeline so that it can run on Vulcan.

Since Vulcan is part of the DL suite of applications, a core advantage and product goal is the ability to seamlessly integrate data from Magma/Metis for further processing. So in order to do this, the pipeline author needs some knowledge of our systems anyways, and for the foreseeable future, those authors are going to be DL engineers. 

### Framework

It is useful to develop a framework for writing pipelines on Vulcan. Getting a pipeline to run on vulcan requires 3 sequential steps:

1. Writing the snakemake pipeline. The pipeline author (DL engineers) should start by writing a fully fledged snakemake pipeline. If the pipeline interacts with our services (ie: query and then **processing** magma records or data back to metis), this should be done in the pipeline. 

2. Deciding what UI components you want for your pipeline parameterization. This involves looking at your config.yaml (which should contain all the inputs for your pipeline) and looking through the UI component catalogue. You then specify these UI components in your `vulcan_config.yaml`.

3. Modifying your snakefile to reflect any changes from step 2. There are a few components that are dynamic and require some pre-processing. The snakefile should contain all inputs and outputs of the pipeline, **even the ones that are required for components**, and hence the workspace `output/` directory (where ouputs) are written to, is the single source of truth for a pipeline.


### Example

Take the scViz pipeline. At a high level the processing involves:

- Querying a processing a record in magma. Writing the processed json 

#### Snakefile


### Notable points
- Processing it must be done in snakemake (and not as a UI job)
-

**Comment by graft** [comment]
A proposal for a step-less version of the vulcan config:

```
params:
- display: "name of single-cell object record"
  ui_component: "pre-populate-dropdown-magma"
  output:
    params: [ "record_name" ]
- display: "Set plot options"
  ui_component: "dynamic-plot-options"
  input:
    single_cell_obj: "output/single_cell_obj.json"
    other_thing: "output/something.json"
  output:
    files:
      plot_settings: "output/plot_settings.json"
- display: "Select bucket location to save plot"
  ui_component: "metis-bucket-dropdown"
  input:
    params: [ "secret_password" ]
    files:
      plot_settings: "output/plot_settings.json"
  param: "bucket_name"
- display: "Download plot"
  input:
    plot_jpg: "output/plot.jpg"
  ui_component: "display-jpg-plot"
```

We also need some kind of component help:
display-jpg-plot - requires input plot_jpg, a jpeg file containing etc.
