### ISSUE TITLE
Vulcan orchestration path definitions not finding complete paths

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#235]
I've been using the `test_workflow.cwl` to build the UI against, and updating it to get the right prompts. However, I think it doesn't find the complete path when there are default inputs for a step. For example, here is my modified CWL file:

```
cwlVersion: v1.1
class: Workflow

inputs:
  someInt:
    type: int
    default: 200
    label: 'it is an int'
  someInt2:
    type: int
    default: 2
    label: 'another int'
  someIntWithoutDefault:
    type: int
    label: 'User supplies a number'

outputs:
  the_result:
    type: int
    outputSource: finalStep/sum

steps:
  firstAdd:
    run: scripts/add.cwl
    label: 'Add two numbers'
    in:
      a: someInt
      b: someInt2
    out: [sum]
  pickANum:
    run: ui-queries/pick-a-number.cwl
    in:
      num: someIntWithoutDefault
    out: [num]
  finalStep:
    run: scripts/add.cwl
    label: 'Add your number to the previous sum'
    in:
      a: firstAdd/sum
      b: pickANum/num
    out: [sum]
```

The output JSON workflow is:

```
{
    "workflows": [
        {
            "class": "Workflow",
            "cwlVersion": "v1.1",
            "name": "umap.cwl",
            "inputs": {
                "someInt": {
                    "label": "it is an int",
                    "type": "int",
                    "format": null,
                    "default": 200
                },
                "someInt2": {
                    "label": "another int",
                    "type": "int",
                    "format": null,
                    "default": 2
                },
                "someIntWithoutDefault": {
                    "label": "User supplies a number",
                    "type": "int",
                    "format": null,
                    "default": null
                }
            },
            "outputs": {
                "the_result": {
                    "outputSource": "finalStep/sum",
                    "label": null,
                    "type": "int",
                    "default": null,
                    "format": null
                }
            },
            "steps": [
                [
                    {
                        "name": "pickANum",
                        "run": "ui-queries/pick-a-number.cwl",
                        "in": [
                            {
                                "id": "num",
                                "source": [
                                    "primary_inputs",
                                    "someIntWithoutDefault"
                                ]
                            }
                        ],
                        "out": [
                            "num"
                        ],
                        "label": null
                    },
                    {
                        "name": "finalStep",
                        "run": "scripts/add.cwl",
                        "in": [
                            {
                                "id": "a",
                                "source": [
                                    "firstAdd",
                                    "sum"
                                ]
                            },
                            {
                                "id": "b",
                                "source": [
                                    "pickANum",
                                    "num"
                                ]
                            }
                        ],
                        "out": [
                            "sum"
                        ],
                        "label": "Add your number to the previous sum"
                    }
                ],
                [
                    {
                        "name": "firstAdd",
                        "run": "scripts/add.cwl",
                        "in": [
                            {
                                "id": "a",
                                "source": [
                                    "primary_inputs",
                                    "someInt"
                                ]
                            },
                            {
                                "id": "b",
                                "source": [
                                    "primary_inputs",
                                    "someInt2"
                                ]
                            }
                        ],
                        "out": [
                            "sum"
                        ],
                        "label": "Add two numbers"
                    },
                    {
                        "name": "finalStep",
                        "run": "scripts/add.cwl",
                        "in": [
                            {
                                "id": "a",
                                "source": [
                                    "firstAdd",
                                    "sum"
                                ]
                            },
                            {
                                "id": "b",
                                "source": [
                                    "pickANum",
                                    "num"
                                ]
                            }
                        ],
                        "out": [
                            "sum"
                        ],
                        "label": "Add your number to the previous sum"
                    }
                ]
            ]
        }
    ]
}
```

Note that there are two paths, each with two steps. One has `pickANum` + `finalStep` while the other has `firstAdd` and `finalStep`. If you use the `test_workflow.cwl` directly, there are two paths in the JSON, the second one has all 3 steps. I would have expected the new JSON to also have one path with all three steps.

I'm going to move ahead with the UI work for now with whatever steps appear, but it does seem like it will affect the UMAP workflow and should be something we address later. Logging this issue here so that we don't forget.
