### ISSUE TITLE
Directed graph assumes a common, shared ancestor

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#253]
The `directed_graph.rb` class hangs when constructing paths, if you provide it a graph without a shared, common ancestor. This is noticeable in Vulcan, if you create a CWL file with an initial "query" input that doesn't require the primary inputs, like:

```
cwlVersion: v1.1
class: Workflow

inputs:
  includeParamA:
    type: boolean
    default: true
    label: 'regress by param A?'
  includeParamB:
    type: boolean
    default: true
    label: 'regress by param B?'
  includeParamC:
    type: boolean
    default: true
    label: 'regress by param C?'
  maxPcs:
    type: int
    default: 15
    label: 'Maximum number of PCs'

outputs:
  the_data:
    type: File
    outputSource: finalStep/sum

steps:
  queryMagma:
    run: scripts/fake_query.cwl
    label: 'Fetch pool record names'
    in: []
    out: [names]
  pickPools:
    run: ui-queries/multiselect-string.cwl
    label: 'Select pool records'
    in:
      a: queryMagma/names
    out: [names]
  doUmapStuff:
    run: scripts/fake_umap_calculations.cwl
    label: 'Do the UMAP stuff'
    in:
      a: pickPools/names
      b: includeParamA
      c: includeParamB
      d: includeParamC
      e: maxPcs
    out: [umap]
  showMe:
    run: ui-outputs/plotly.cwl
    in:
      a: doUmapStuff/umap
    out: []
    label: 'UMAP'
  convertToConsignment:
    run: scripts/convert_to_consignment.cwl
    label: 'Convert data to TSV'
    in:
      a: doUmapStuff/umap
    out: [output]
  downloadRawData:
    run: ui-outputs/consignment.cwl
    in:
      a: convertToConsignment/output
    out: []
    label: 'Download Raw Data as TSV'
```

The path calculation algorithm will hang. The simple fix currently is to just add the primary inputs to the first "work step", even if they aren't required. Like:

```
cwlVersion: v1.1
class: Workflow

inputs:
  includeParamA:
    type: boolean
    default: true
    label: 'regress by param A?'
  includeParamB:
    type: boolean
    default: true
    label: 'regress by param B?'
  includeParamC:
    type: boolean
    default: true
    label: 'regress by param C?'
  maxPcs:
    type: int
    default: 15
    label: 'Maximum number of PCs'

outputs:
  the_data:
    type: File
    outputSource: finalStep/sum

steps:
  queryMagma:
    run: scripts/fake_query.cwl
    label: 'Fetch pool record names'
    in:
      b: includeParamA
      c: includeParamB
      d: includeParamC
      e: maxPcs
    out: [names]
  pickPools:
    run: ui-queries/multiselect-string.cwl
    label: 'Select pool records'
    in:
      a: queryMagma/names
    out: [names]
  doUmapStuff:
    run: scripts/fake_umap_calculations.cwl
    label: 'Do the UMAP stuff'
    in:
      a: pickPools/names
      b: includeParamA
      c: includeParamB
      d: includeParamC
      e: maxPcs
    out: [umap]
  showMe:
    run: ui-outputs/plotly.cwl
    in:
      a: doUmapStuff/umap
    out: []
    label: 'UMAP'
  convertToConsignment:
    run: scripts/convert_to_consignment.cwl
    label: 'Convert data to TSV'
    in:
      a: doUmapStuff/umap
    out: [output]
  downloadRawData:
    run: ui-outputs/consignment.cwl
    in:
      a: convertToConsignment/output
    out: []
    label: 'Download Raw Data as TSV'
```
